### ISSUE TITLE
Switch to using group_vars directories

### ISSUE THREAD

**Issue by dpoirier** [caktus/tequila#6]
Currently we use vars files like this:

```
group_vars/all
secrets/all
group_vars/<env_name>
secrets/<env_name>
```

If we change to this layout:

```
group_vars/all/vars.yml
group_vars/all/secrets.yml
group_vars/<envname>/vars.yml
group_vars/<envname>/secrets.yml
```

We'd get at least two advantages:
- Our YAML files would have a file extension that would tell our editors what their syntax is.
- Ansible would automatically load all the files in the relevant group directories. Right now, `deploy.py` has to include the secrets files on the command line, and we could stop doing that.

I would like for `deploy.py` to add as little magic as possible, by doing things in a way that Ansible can pick up on itself, and this is a step in that direction.

Opinions?

**Comment by Scottm-Caktus** [comment]
This looks like it would be more straight forward. Are there any downsides to doing it this way?

**Comment by dpoirier** [comment]
I can't think of any real downsides. I should probably just go ahead with this.

**Comment by dpoirier** [comment]
Changed in 8c36416.
